# Copyright 2026 Renesas Electronics Corporation
# SPDX-License-Identifier: Apache-2.0

CONFIG_FLASH=y
CONFIG_MEMC=y

# USER NEED UPDATE AFTER EACH TIME EXPORT MODEL
CONFIG_AI_INPUT_QUANT_SCALE="0.007808685302734375"
CONFIG_AI_INPUT_QUANT_ZERO_POINT=0
CONFIG_AI_OUTPUT_QUANT_SCALE="0.10048583149909973"
CONFIG_AI_OUTPUT_QUANT_ZERO_POINT=127

# cortex-m85 specific configurations
# CONFIG_EXECUTORCH_TEMP_ALLOCATOR_POOL_SIZE=0
# CONFIG_EXECUTORCH_METHOD_ALLOCATOR_POOL_SIZE=900000

# ETHOS-U specific configurations
CONFIG_ETHOS_U=y
CONFIG_EXECUTORCH_TEMP_ALLOCATOR_POOL_SIZE=804928
CONFIG_EXECUTORCH_METHOD_ALLOCATOR_POOL_SIZE=452880

CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=5200282
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=8
CONFIG_VIDEO_BUFFER_POOL_ZEPHYR_REGION=y
CONFIG_VIDEO_BUFFER_POOL_ZEPHYR_REGION_NAME="SDRAM"

CONFIG_LV_USE_DRAW_DAVE2D=y
CONFIG_RENESAS_DAVE2D_RUNTIME_HEAP_SIZE=49752

# VDB routed to SDRAM (overrides prj.conf's default region for this board).
CONFIG_LV_Z_VDB_ZEPHYR_REGION=y
CONFIG_LV_Z_VDB_ZEPHYR_REGION_NAME="SDRAM"

CONFIG_LV_Z_USE_OSAL=y
CONFIG_LV_DRAW_THREAD_PRIO=-2

CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_ALLOC=y

CONFIG_DCACHE=y
CONFIG_CACHE_MANAGEMENT=y
