CONFIG_FLASH=y
CONFIG_CRC=y
CONFIG_HEAP_MEM_POOL_SIZE=65536
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETCHAR=y
CONFIG_CONSOLE_GETCHAR_BUFSIZE=8192
CONFIG_CONSOLE_PUTCHAR_BUFSIZE=256
