CONFIG_SHELL=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_USB_HOST_STACK=y
CONFIG_USBH_SHELL=y

CONFIG_LOG=y
CONFIG_USBH_LOG_LEVEL_WRN=y
CONFIG_USBH_HID_LOG_LEVEL_DBG=y
CONFIG_UHC_DRIVER_LOG_LEVEL_WRN=y

CONFIG_UHC_RENESAS_RA_OSC_WAIT_RETRIES=20

CONFIG_USBH_HID_CLASS=y
CONFIG_USBH_DFU_CLASS=n
CONFIG_USBH_HID_ROUTE_TO_INPUT=y
CONFIG_INPUT=y

CONFIG_DEBUG_OPTIMIZATIONS=y
